### PR TITLE
Add search box

### PR DESCRIPTION
**Pull request by priyanshsaxena**
Search-box added. Lets you search for places by name, and adds markers to all of them. The map gets centered on the first location searched.

### CODE REVIEW

**Comment by ankita132** [comment]
the same error for the firebase occurs here as well.

**Comment by priyanshsaxena** [comment]
Fixed the error. Please review again.

**Comment by priyanshsaxena** [comment]
@ankita132 I fixed the issues mentioned. The image-upload feature worked for your database (if the database has some inspirational quote in a black background, I uploaded that). Please review again, and we can discuss this in the forum further.

**Comment by ankita132** [comment]
works fine for me

**Pull request merged**
